### create
POST http://127.0.0.1:8090/api/todos
Content-Type: application/json

{
    "content": "blabla"
}

### delete
DELETE http://127.0.0.1:8090/api/todos/651328f375fcb3e1d35341cf
### edit content

### mard done/undone
PATCH http://127.0.0.1:8090/api/todos/651328f375fcb3e1d35341cf
Content-Type: application/json

{
    "isDone": true
}

### view all
GET http://127.0.0.1:8090/api/todos